@startuml
!theme mars
skinparam backgroundColor #00000000
title
  | id | Age | Disease |
  | 1 | <14 | B |
  | 2 | >14 | A |
  | 3 | >14 | B |
  | 4 | <14 | A |
  | 5 | >14 | B |
  | 6 | <14  | A |
end title
@enduml